package pc;

public interface ErrorCode {

	String XML_ORDER_NOT_FOUND="XX00XNF";
	String ZERO_FILE_FOUND="XX00ZF";
	String FTP_ZERO_FILE_FOUND="XX00FZF";
	String FILE_NOT_FOUND="XX00NF";
	String AID_FILE_NOT_FOUND="XX00ANF";
	String ZIP_FILE_NOT_FOUND_FTP="XX21ZNF";
	String XML_FILE_NOT_FOUND_FTP="XX21XNF";
	String PATH_NOT_CONNECTED="XX99PNC";
	String SKIP_PC_XML="XX98SKPC";
	String WORKFLOW_NOT_FOUND="XX98WNF";
	
}
